import Head from 'next/head'
import Header from './components/Header'
import Main from './components/Main'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sunnyside</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
    </>
  )
}
